name: Bug Report
description: File a bug report
title: "bug(COMPONENT): TITLE"
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: Provide version of software.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What is expected
    validations:
      required: true
  - type: textarea
    id: happening
    attributes:
      label: What is actually happening
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Url
      placeholder: provide a link to a minimal reproduction of the bug.
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      description: provide browser to a minimal reproduction of the bug?
      options:
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: false
  - type: textarea
    id: additionalComments
    attributes:
      label: Any additional comments
    validations:
      required: false
