name: Bug Report
description: File a bug report
title: "bug(COMPONENT): TITLE"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a brief description about bug.
      value: 'value'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Provide version of software.
      value: 'value'
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Url?
      description: provide a link to a minimal reproduction of the bug.
      value: 'value'
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: provide browser to a minimal reproduction of the bug?
      options:
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: false
