name: Bug Report
description: File a bug report
title: "bug(COMPONENT): TITLE"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Provide a brief description about bug.
      value: 'value'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      value: 'value'
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Url?
      description: url
      value: 'value'
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      - Chrome
      - Safari
      - Microsoft Edge
