name: Bug Report
description: File a bug report
title: "bug(COMPONENT): TITLE"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      placeholder: Provide a brief description about bug.
      value: ''
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: Provide version of software.
      value: ''
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Url?
      placeholder: provide a link to a minimal reproduction of the bug.
      value: ''
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      placeholder: provide browser to a minimal reproduction of the bug?
      options:
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: false
