
name: Documentation
description: Documentation
title: 'docs(COMPONENT): TITLE'
labels: ['docs']
body:
  - type: dropdown
    id: name
    attributes:
      label: Component
      options:
        - deps
        - cdk
        - schematics
        - variables
        - core
        - action
        - testing
        - shared
        - types
        - util
        - styles
        - action-menu
        - alert
        - arrow-switcher
        - copy
        - autocomplete
        - avatar
        - badge
        - breadcrumb
        - button
        - card
        - cascader
        - checkbox
        - date-picker
        - date-range
        - datepicker
        - dialog
        - directive
        - drag-drop
        - dropdown
        - empty
        - flexible-text
        - form
        - grid
        - table
        - icon
        - input
        - label
        - tag
        - layout
        - link
        - list
        - loading
        - markdown
        - mention
        - menu
        - nav
        - notify
        - pagination
        - popover
        - progress
        - property-operation
        - radio
        - result
        - select
        - skeleton
        - slide
        - slider
        - statistic
        - stepper
        - store
        - strength
        - switch
        - time-picker
        - tooltip
        - transfer
        - tree
        - tree-select
        - upload
        - vote
        - anchor
        - back-top
        - timeline
        - divider
        - space
        - calendar
        - fullscreen
        - guider
        - resizable
        - input-number
        - collapse
        - rate
        - select-control
        - image
        - segment
        - dot
    validations:
      required: false
  - type: textarea
    attributes:
      label: Description
      placeholder: Provide a brief summary of what you would like to see changed in our documentation.
    validations:
      required: true
 