name: Feature request
description: Suggest an idea for this project
title: 'feat(COMPONENT): TITLE'
labels: ['feature']
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Provide a brief summary of the feature you would like to see.
      value: 'value'
    validations:
      required: true
  - type: textarea
    id: case
    attributes:
      label: Use Case
      description: Describe the use case(s) that the proposed feature would enable.
      value: 'value'
    validations:
      required: true
