name: Feature request
description: Suggest an idea for this project
title: 'feat(COMPONENT): TITLE'
labels: ['feature']
body:
  - type: markdown
    attributes:
      label: Feature Description
      id: description
      description: Provide a brief summary of the feature you would like to see.
      value: value
    validations:
      required: true
  - type: markdown
    attributes:
      label: Use Case
      id: case
      description: Describe the use case(s) that the proposed feature would enable.
      value: value
    validations:
      required: true
