name: AutoMerge

on:
  pull_request:
    types:
     - opened
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  console_log:
    runs-on: ubuntu-latest
    steps:
       - run: echo '${{toJSON(github)}}'
  run_if:
    if:  startsWith(github.head_ref, 'release-auto-')
  # 合并发布版本的 pr 到 master
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        uses: 'pascalgn/automerge-action@v0.14.3'
        env:
          GITHUB_TOKEN: '${{ secrets.RELEASE_TOKEN }}'
          MERGE_LABELS: ''
      - name: Release
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name:  Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - run: echo '${{toJSON(secrets)}}'
      - name: Publish
        run: npm run pub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
